// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: macro/pricesaggregator/asset.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Asset struct {
	// id of asset on chain
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// denom of token on macro chain
	Denom string `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	// symbol of token
	Symbol string `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// exchange rates asset/usd with multiplier
	ExchangeRates github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,4,opt,name=exchange_rates,json=exchangeRates,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"exchange_rates" yaml:"exchange_rates"`
	// update_time is the time at which the last exchange_rates updated.
	UpdateTime time.Time `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3,stdtime" json:"update_time" yaml:"update_time"`
	// accepted_duration is the period from update_time that exchange_rates is accepted
	AcceptedDuration time.Duration `protobuf:"bytes,6,opt,name=accepted_duration,json=acceptedDuration,proto3,stdduration" json:"duration,omitempty" yaml:"accepted_duration"`
}

func (m *Asset) Reset()         { *m = Asset{} }
func (m *Asset) String() string { return proto.CompactTextString(m) }
func (*Asset) ProtoMessage()    {}
func (*Asset) Descriptor() ([]byte, []int) {
	return fileDescriptor_8585e64f912984f2, []int{0}
}
func (m *Asset) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Asset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Asset.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Asset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Asset.Merge(m, src)
}
func (m *Asset) XXX_Size() int {
	return m.Size()
}
func (m *Asset) XXX_DiscardUnknown() {
	xxx_messageInfo_Asset.DiscardUnknown(m)
}

var xxx_messageInfo_Asset proto.InternalMessageInfo

func (m *Asset) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Asset) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *Asset) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Asset) GetUpdateTime() time.Time {
	if m != nil {
		return m.UpdateTime
	}
	return time.Time{}
}

func (m *Asset) GetAcceptedDuration() time.Duration {
	if m != nil {
		return m.AcceptedDuration
	}
	return 0
}

func init() {
	proto.RegisterType((*Asset)(nil), "macro.pricesaggregator.Asset")
}

func init() {
	proto.RegisterFile("macro/pricesaggregator/asset.proto", fileDescriptor_8585e64f912984f2)
}

var fileDescriptor_8585e64f912984f2 = []byte{
	// 423 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0x31, 0x6f, 0xd3, 0x40,
	0x14, 0xce, 0xa5, 0x4d, 0x24, 0xae, 0xa2, 0x82, 0x53, 0xa9, 0x4c, 0x06, 0x5f, 0xe4, 0x01, 0x65,
	0xa0, 0x3e, 0x41, 0x87, 0x4a, 0xdd, 0x88, 0x2a, 0x31, 0xb1, 0x58, 0x4c, 0x30, 0x44, 0x97, 0xf3,
	0x71, 0xb5, 0xc8, 0xf9, 0x59, 0xbe, 0x33, 0xaa, 0x57, 0x7e, 0x41, 0x37, 0xf8, 0x49, 0x1d, 0x3b,
	0x22, 0x06, 0x83, 0x92, 0x8d, 0x31, 0xbf, 0x00, 0x9d, 0xcf, 0x46, 0xa1, 0x99, 0xec, 0xf7, 0xbd,
	0xef, 0x7d, 0xdf, 0x7d, 0x4f, 0x0f, 0x47, 0x9a, 0x8b, 0x12, 0x58, 0x51, 0x66, 0x42, 0x1a, 0xae,
	0x54, 0x29, 0x15, 0xb7, 0x50, 0x32, 0x6e, 0x8c, 0xb4, 0x71, 0x51, 0x82, 0x05, 0x72, 0xda, 0x72,
	0xe2, 0x87, 0x9c, 0xc9, 0x89, 0x02, 0x05, 0x2d, 0x85, 0xb9, 0x3f, 0xcf, 0x9e, 0x84, 0x0a, 0x40,
	0xad, 0x24, 0x6b, 0xab, 0x65, 0xf5, 0x89, 0xa5, 0x55, 0xc9, 0x6d, 0x06, 0x79, 0xd7, 0xa7, 0x0f,
	0xfb, 0x36, 0xd3, 0xd2, 0x58, 0xae, 0x0b, 0x4f, 0x88, 0xbe, 0x1d, 0xe0, 0xd1, 0x1b, 0x67, 0x4f,
	0x8e, 0xf1, 0x30, 0x4b, 0x03, 0x34, 0x45, 0xb3, 0xc3, 0x64, 0x98, 0xa5, 0xe4, 0x04, 0x8f, 0x52,
	0x99, 0x83, 0x0e, 0x86, 0x53, 0x34, 0x7b, 0x94, 0xf8, 0x82, 0x9c, 0xe2, 0xb1, 0xa9, 0xf5, 0x12,
	0x56, 0xc1, 0x41, 0x0b, 0x77, 0x15, 0xc9, 0xf1, 0xb1, 0xbc, 0x11, 0xd7, 0x3c, 0x57, 0x72, 0x51,
	0x72, 0x2b, 0x4d, 0x70, 0xe8, 0xfa, 0xf3, 0xb7, 0x77, 0x0d, 0x1d, 0xfc, 0x6c, 0xe8, 0x0b, 0x95,
	0xd9, 0xeb, 0x6a, 0x19, 0x0b, 0xd0, 0x4c, 0x80, 0xd1, 0x60, 0xba, 0xcf, 0x99, 0x49, 0x3f, 0x33,
	0x5b, 0x17, 0xd2, 0xc4, 0x57, 0x52, 0x6c, 0x1b, 0xfa, 0xac, 0xe6, 0x7a, 0x75, 0x19, 0xfd, 0xaf,
	0x16, 0x25, 0x8f, 0x7b, 0x20, 0x71, 0x35, 0xf9, 0x88, 0x8f, 0xaa, 0x22, 0xe5, 0x56, 0x2e, 0x5c,
	0xa2, 0x60, 0x34, 0x45, 0xb3, 0xa3, 0xd7, 0x93, 0xd8, 0xc7, 0x8d, 0xfb, 0xb8, 0xf1, 0xfb, 0x3e,
	0xee, 0x3c, 0x74, 0x0f, 0xd9, 0x36, 0x94, 0x78, 0xf9, 0x9d, 0xe1, 0xe8, 0xf6, 0x17, 0x45, 0x09,
	0xf6, 0x88, 0x1b, 0x20, 0x5f, 0x11, 0x7e, 0xca, 0x85, 0x90, 0x85, 0x95, 0xe9, 0xa2, 0xdf, 0x68,
	0x30, 0x6e, 0x3d, 0x9e, 0xef, 0x79, 0x5c, 0x75, 0x84, 0xf9, 0xa5, 0xb3, 0xf8, 0xd3, 0x50, 0xd2,
	0x8f, 0xbc, 0x04, 0x9d, 0x59, 0xa9, 0x0b, 0x5b, 0x6f, 0x1b, 0x1a, 0x78, 0xe3, 0x3d, 0xdd, 0xe8,
	0xbb, 0xb3, 0x7f, 0xd2, 0xe3, 0xff, 0xd4, 0xde, 0xdd, 0xad, 0x43, 0x74, 0xbf, 0x0e, 0xd1, 0xef,
	0x75, 0x88, 0x6e, 0x37, 0xe1, 0xe0, 0x7e, 0x13, 0x0e, 0x7e, 0x6c, 0xc2, 0xc1, 0x87, 0xf3, 0x9d,
	0x5d, 0x7e, 0xa9, 0x20, 0x57, 0xaf, 0x2e, 0x2e, 0x98, 0x3f, 0xad, 0x9b, 0xee, 0xb8, 0xce, 0x76,
	0xae, 0xab, 0x5d, 0xee, 0x72, 0xdc, 0xbe, 0xf7, 0xfc, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9a,
	0xba, 0x4d, 0x5b, 0x84, 0x02, 0x00, 0x00,
}

func (m *Asset) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Asset) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Asset) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.AcceptedDuration, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.AcceptedDuration):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintAsset(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x32
	n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.UpdateTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.UpdateTime):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintAsset(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x2a
	{
		size := m.ExchangeRates.Size()
		i -= size
		if _, err := m.ExchangeRates.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintAsset(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Symbol) > 0 {
		i -= len(m.Symbol)
		copy(dAtA[i:], m.Symbol)
		i = encodeVarintAsset(dAtA, i, uint64(len(m.Symbol)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintAsset(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintAsset(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintAsset(dAtA []byte, offset int, v uint64) int {
	offset -= sovAsset(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Asset) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovAsset(uint64(m.Id))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovAsset(uint64(l))
	}
	l = len(m.Symbol)
	if l > 0 {
		n += 1 + l + sovAsset(uint64(l))
	}
	l = m.ExchangeRates.Size()
	n += 1 + l + sovAsset(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.UpdateTime)
	n += 1 + l + sovAsset(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.AcceptedDuration)
	n += 1 + l + sovAsset(uint64(l))
	return n
}

func sovAsset(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAsset(x uint64) (n int) {
	return sovAsset(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Asset) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAsset
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Asset: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Asset: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAsset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAsset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAsset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAsset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Symbol", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAsset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAsset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAsset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Symbol = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExchangeRates", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAsset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAsset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAsset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ExchangeRates.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdateTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAsset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAsset
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAsset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.UpdateTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AcceptedDuration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAsset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAsset
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAsset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.AcceptedDuration, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAsset(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAsset
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAsset(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAsset
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAsset
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAsset
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAsset
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAsset
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAsset
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAsset        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAsset          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAsset = fmt.Errorf("proto: unexpected end of group")
)
