// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: macro/pricesaggregator/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgAddAssetPricesTrackingList struct {
	// authority is the address that controls the module (defaults to x/gov unless
	// overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty" yaml:"authority"`
	// denom of token on macro chain
	Denom string `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	// symbol of token
	Symbol string `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
}

func (m *MsgAddAssetPricesTrackingList) Reset()         { *m = MsgAddAssetPricesTrackingList{} }
func (m *MsgAddAssetPricesTrackingList) String() string { return proto.CompactTextString(m) }
func (*MsgAddAssetPricesTrackingList) ProtoMessage()    {}
func (*MsgAddAssetPricesTrackingList) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f72e74c9f96d2eb, []int{0}
}
func (m *MsgAddAssetPricesTrackingList) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddAssetPricesTrackingList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddAssetPricesTrackingList.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddAssetPricesTrackingList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddAssetPricesTrackingList.Merge(m, src)
}
func (m *MsgAddAssetPricesTrackingList) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddAssetPricesTrackingList) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddAssetPricesTrackingList.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddAssetPricesTrackingList proto.InternalMessageInfo

func (m *MsgAddAssetPricesTrackingList) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgAddAssetPricesTrackingList) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *MsgAddAssetPricesTrackingList) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type MsgAddAssetPricesTrackingListResponse struct {
	// id of asset on macro chain
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgAddAssetPricesTrackingListResponse) Reset()         { *m = MsgAddAssetPricesTrackingListResponse{} }
func (m *MsgAddAssetPricesTrackingListResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAddAssetPricesTrackingListResponse) ProtoMessage()    {}
func (*MsgAddAssetPricesTrackingListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f72e74c9f96d2eb, []int{1}
}
func (m *MsgAddAssetPricesTrackingListResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddAssetPricesTrackingListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddAssetPricesTrackingListResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddAssetPricesTrackingListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddAssetPricesTrackingListResponse.Merge(m, src)
}
func (m *MsgAddAssetPricesTrackingListResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddAssetPricesTrackingListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddAssetPricesTrackingListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddAssetPricesTrackingListResponse proto.InternalMessageInfo

func (m *MsgAddAssetPricesTrackingListResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgAddAssetPricesTrackingList)(nil), "macro.pricesaggregator.MsgAddAssetPricesTrackingList")
	proto.RegisterType((*MsgAddAssetPricesTrackingListResponse)(nil), "macro.pricesaggregator.MsgAddAssetPricesTrackingListResponse")
}

func init() { proto.RegisterFile("macro/pricesaggregator/tx.proto", fileDescriptor_2f72e74c9f96d2eb) }

var fileDescriptor_2f72e74c9f96d2eb = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0x4f, 0x4b, 0xc3, 0x30,
	0x18, 0x87, 0x97, 0x4d, 0x07, 0xcb, 0x41, 0xa4, 0x8c, 0x31, 0x0a, 0x66, 0x52, 0x10, 0xbc, 0xd8,
	0xb0, 0x0d, 0x19, 0x08, 0x1e, 0xb6, 0xb3, 0x03, 0x29, 0x9e, 0xbc, 0xa5, 0x6d, 0xc8, 0x82, 0x6b,
	0xdf, 0x92, 0x37, 0x1b, 0xeb, 0xd1, 0x6f, 0x20, 0x1e, 0xfd, 0x44, 0x1e, 0x77, 0xf4, 0x24, 0xb2,
	0x7d, 0x03, 0x3f, 0x81, 0xac, 0x9d, 0x7f, 0x10, 0xd9, 0xc1, 0x5b, 0xde, 0xbc, 0x4f, 0x92, 0x5f,
	0xde, 0x87, 0x76, 0x12, 0x11, 0x19, 0xe0, 0x99, 0xd1, 0x91, 0x44, 0xa1, 0x94, 0x91, 0x4a, 0x58,
	0x30, 0xdc, 0x2e, 0xfc, 0xcc, 0x80, 0x05, 0xa7, 0x55, 0x00, 0xfe, 0x6f, 0xc0, 0x6d, 0x2a, 0x50,
	0x50, 0x20, 0x7c, 0xb3, 0x2a, 0x69, 0x97, 0x45, 0x80, 0x09, 0x20, 0x0f, 0x05, 0x4a, 0x3e, 0xef,
	0x86, 0xd2, 0x8a, 0x2e, 0x8f, 0x40, 0xa7, 0x65, 0xdf, 0xbb, 0x27, 0xf4, 0x68, 0x8c, 0x6a, 0x18,
	0xc7, 0x43, 0x44, 0x69, 0xaf, 0x8b, 0x5b, 0x6f, 0x8c, 0x88, 0xee, 0x74, 0xaa, 0xae, 0x34, 0x5a,
	0xa7, 0x47, 0x1b, 0x62, 0x66, 0x27, 0x60, 0xb4, 0xcd, 0xdb, 0xe4, 0x98, 0x9c, 0x36, 0x46, 0xcd,
	0xf7, 0xd7, 0xce, 0x61, 0x2e, 0x92, 0xe9, 0x85, 0xf7, 0xd5, 0xf2, 0x82, 0x6f, 0xcc, 0x69, 0xd2,
	0xfd, 0x58, 0xa6, 0x90, 0xb4, 0xab, 0x1b, 0x3e, 0x28, 0x0b, 0xa7, 0x45, 0xeb, 0x98, 0x27, 0x21,
	0x4c, 0xdb, 0xb5, 0x62, 0x7b, 0x5b, 0x79, 0x03, 0x7a, 0xb2, 0x33, 0x42, 0x20, 0x31, 0x83, 0x14,
	0xa5, 0x73, 0x40, 0xab, 0x3a, 0x2e, 0x32, 0xec, 0x05, 0x55, 0x1d, 0xf7, 0x9e, 0x08, 0xad, 0x8d,
	0x51, 0x39, 0x8f, 0x84, 0xba, 0x3b, 0x7e, 0x70, 0xee, 0xff, 0x3d, 0x32, 0x7f, 0xe7, 0xab, 0xee,
	0xe5, 0xbf, 0x8e, 0x7d, 0x86, 0x1d, 0x8d, 0x9f, 0x57, 0x8c, 0x2c, 0x57, 0x8c, 0xbc, 0xad, 0x18,
	0x79, 0x58, 0xb3, 0xca, 0x72, 0xcd, 0x2a, 0x2f, 0x6b, 0x56, 0xb9, 0xed, 0x2b, 0x6d, 0x27, 0xb3,
	0xd0, 0x8f, 0x20, 0xe1, 0xf3, 0x19, 0xa4, 0xaa, 0x3b, 0x18, 0xf0, 0x52, 0xfb, 0x62, 0x2b, 0xfe,
	0xec, 0xa7, 0xf9, 0x3c, 0x93, 0x18, 0xd6, 0x0b, 0x5f, 0xfd, 0x8f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x2b, 0x31, 0x69, 0x11, 0x20, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	AddAssetPricesTrackingList(ctx context.Context, in *MsgAddAssetPricesTrackingList, opts ...grpc.CallOption) (*MsgAddAssetPricesTrackingListResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) AddAssetPricesTrackingList(ctx context.Context, in *MsgAddAssetPricesTrackingList, opts ...grpc.CallOption) (*MsgAddAssetPricesTrackingListResponse, error) {
	out := new(MsgAddAssetPricesTrackingListResponse)
	err := c.cc.Invoke(ctx, "/macro.pricesaggregator.Msg/AddAssetPricesTrackingList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	AddAssetPricesTrackingList(context.Context, *MsgAddAssetPricesTrackingList) (*MsgAddAssetPricesTrackingListResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) AddAssetPricesTrackingList(ctx context.Context, req *MsgAddAssetPricesTrackingList) (*MsgAddAssetPricesTrackingListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAssetPricesTrackingList not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_AddAssetPricesTrackingList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAddAssetPricesTrackingList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AddAssetPricesTrackingList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/macro.pricesaggregator.Msg/AddAssetPricesTrackingList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AddAssetPricesTrackingList(ctx, req.(*MsgAddAssetPricesTrackingList))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "macro.pricesaggregator.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddAssetPricesTrackingList",
			Handler:    _Msg_AddAssetPricesTrackingList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "macro/pricesaggregator/tx.proto",
}

func (m *MsgAddAssetPricesTrackingList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddAssetPricesTrackingList) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddAssetPricesTrackingList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Symbol) > 0 {
		i -= len(m.Symbol)
		copy(dAtA[i:], m.Symbol)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Symbol)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAddAssetPricesTrackingListResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddAssetPricesTrackingListResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddAssetPricesTrackingListResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgAddAssetPricesTrackingList) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Symbol)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgAddAssetPricesTrackingListResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgAddAssetPricesTrackingList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddAssetPricesTrackingList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddAssetPricesTrackingList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Symbol", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Symbol = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddAssetPricesTrackingListResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddAssetPricesTrackingListResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddAssetPricesTrackingListResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
